name: Docker Image 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t emp .
    - name: Tag the Docker image
      run: docker tag emp omkarpadmane/nodejs
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker image push
      run: docker push omkarpadmane/nodejs


  
